export const ABRIDGED_INVOICES_LOADED = "ABRIDGED_INVOICES_LOADED";
export const INVOICES_FILTERED = "INVOICES_FILTERED";
export const EDITOR_TOGGLED = "EDITOR_TOGGLED";
export const EDITED_AT_INDEX = "EDITED_AT_INDEX";
//export const CONFIRMING_DELETE = "CONFIRMING_DELETE";
export const OPENING_DELETE_CONFIRMATION = "OPENING_DELETE_CONFIRMATION";

export const NAME_CHANGED = "NAME_CHANGED";
export const AMOUNT_CHANGED = "AMOUNT_CHANGED";
export const STATUS_CHANGED = "STATUS_CHANGED";
export const COUNTRY_CHANGED = "COUNTRY_CHANGED";
export const CITY_CHANGED = "CITY_CHANGED";
export const PHONE_CHANGED = "PHONE_CHANGED";

export const ANONYMOUS_FINANCES_LOADED = "ANONYMOUS_FINANCES_LOADED";